# Generated by Django 5.1.1 on 2024-10-01 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lecturer', models.CharField(max_length=100)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
